CREATE DATABASE aml_kyt;
CREATE DATABASE audit;
CREATE DATABASE identity_auth;
CREATE DATABASE liquidity;
CREATE DATABASE onboarding_kyc;
CREATE DATABASE policy_engine;
CREATE DATABASE reconciliation;
CREATE DATABASE treasury;
CREATE DATABASE wallet_management;
